INSERT INTO characters (name, fighter_number, image_slug) VALUES
  ('Mario', '01', 'mario'),
  ('Donkey Kong', '02', 'donkey_kong'),
  ('Link', '03', 'link'),
  ('Samus', '04', 'samus'),
  ('Dark Samus', '04ε', 'dark_samus'),
  ('Yoshi', '05', 'yoshi'),
  ('Kirby', '06', 'kirby'),
  ('Fox', '07', 'fox'),
  ('Pikachu', '08', 'pikachu'),
  ('Luigi', '09', 'luigi'),
  ('Ness', '10', 'ness'),
  ('Captain Falcon', '11', 'captain_falcon'),
  ('Jigglypuff', '12', 'jigglypuff'),
  ('Peach', '13', 'peach'),
  ('Daisy', '13ε', 'daisy'),
  ('Bowser', '14', 'bowser'),
  ('Ice Climbers', '15', 'ice_climbers'),
  ('Sheik', '16', 'sheik'),
  ('Zelda', '17', 'zelda'),
  ('Dr. Mario', '18', 'dr_mario'),
  ('Pichu', '19', 'pichu'),
  ('Falco', '20', 'falco'),
  ('Marth', '21', 'marth'),
  ('Lucina', '21ε', 'lucina'),
  ('Young Link', '22', 'young_link'),
  ('Ganondorf', '23', 'ganondorf'),
  ('Mewtwo', '24', 'mewtwo'),
  ('Roy', '25', 'roy'),
  ('Chrom', '25ε', 'chrom'),
  ('Mr. Game & Watch', '26', 'mr_game_and_watch'),
  ('Meta Knight', '27', 'meta_knight'),
  ('Pit', '28', 'pit'),
  ('Dark Pit', '28ε', 'dark_pit'),
  ('Zero Suit Samus', '29', 'zero_suit_samus'),
  ('Wario', '30', 'wario'),
  ('Snake', '31', 'snake'),
  ('Ike', '32', 'ike'),
  ('Pokemon Trainer', '33-35', 'pokemon_trainer'),
  ('Diddy Kong', '36', 'diddy_kong'),
  ('Lucas', '37', 'lucas'),
  ('Sonic', '38', 'sonic'),
  ('King Dedede', '39', 'king_dedede'),
  ('Olimar', '40', 'pikmin_and_olimar'),
  ('Lucario', '41', 'lucario'),
  ('R.O.B.', '42', 'robot'),
  ('Toon Link', '43', 'toon_link'),
  ('Wolf', '44', 'wolf'),
  ('Villager', '45', 'villager'),
  ('Mega Man', '46', 'mega_man'),
  ('Wii Fit Trainer', '47', 'wii_fit_trainer'),
  ('Rosalina & Luma', '48', 'rosalina_and_luma'),
  ('Little Mac', '49', 'little_mac'),
  ('Greninja', '50', 'greninja'),
  ('Mii Brawler', '51', 'mii_fighter'),
  ('Mii Swordfighter', '52', 'mii_fighter'),
  ('Mii Gunner', '53', 'mii_fighter'),
  ('Palutena', '54', 'palutena'),
  ('Pac-Man', '55', 'pac_man'),
  ('Robin', '56', 'robin'),
  ('Shulk', '57', 'shulk'),
  ('Bowser Jr.', '58', 'bowser_jr'),
  ('Duck Hunt', '59', 'duck_hunt'),
  ('Ryu', '60', 'ryu'),
  ('Ken', '60ε', 'ken'),
  ('Cloud', '61', 'cloud'),
  ('Corrin', '62', 'corrin'),
  ('Bayonetta', '63', 'bayonetta'),
  ('Inkling', '64', 'inkling'),
  ('Ridley', '65', 'ridley'),
  ('Simon', '66', 'simon'),
  ('Richter', '66ε', 'richter'),
  ('King K. Rool', '67', 'king_k_rool'),
  ('Isabelle', '68', 'shizue'),
  ('Incineroar', '69', 'gaogaen'),
  ('Piranha Plant', '70', 'packun_flower'),
  ('Joker', '71', 'joker'),
  ('Hero', '72', 'dq_hero'),
  ('Banjo & Kazooie', '73', 'banjo_and_kazooie'),
  ('Terry', '74', 'terry'),
  ('Byleth', '75', 'byleth'),
  ('Min Min', '76', 'minmin'),
  ('Steve', '77', 'steve'),
  ('Sephiroth', '78', 'sephiroth'),
  ('Pyra / Mythra', '79-80', 'homura'),
  ('Kazuya', '81', 'kazuya'),
  ('Sora', '82', 'sora');
